[package]
name = "ccwc"
version = "0.1.0"
edition = "2021"
description = "A simple implementation of the wc command"
authors = ["Your Name"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
