name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests on ccwc
      run: cargo test --manifest-path ccwc/Cargo.toml
    - name: Run tests on json_parser
      run: cargo test --manifest-path json_parser/Cargo.toml
